version: "3.9"
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/

  backend:
    build: backend
    ports:
      - 15001:15001
    depends_on:
      - db
    environment:
      - SHORT_LINK_BASE=http://localhost:15001/
      - POSTGRES_CONN_STRING=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
      - ALLOW_CORS_FROM=http://localhost:8080/
    command: --use-db

  frontend:
    build: frontend
    ports:
      - 8080:80
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:15001/

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.org
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin

volumes:
  database-data:
  pgadmin:
